name: shubhchintak
description: SHUBHCHINTAK - Privacy-first QR-based safety and contact platform.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  qr_flutter: ^4.1.0
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  intl: ^0.19.0
  badges: ^3.1.2
  google_sign_in: ^6.2.1
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.0
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/